### ISSUE TITLE
Multiple request in one test method.

### ISSUE THREAD

**Issue by bcho** [there4/slim-unit-testing-example#1]
When I try to run multiple request in one test method, for example:

``` php
    public function testRoutesIdCondition()
    {
        $this->get('/user/1');
        $this->assertEquals(200, $this->response->status());

        $this->get('/user/1a');
        $this->assertEquals(404, $this->response->status());

        $this->get('/category/1a');
        $this->assertEquals(404, $this->response->status());
    }
```

The following requests are unable to get the correct `response`. (i.e., the remains requests will get a 200 instead of 404)

Maybe re-setup the mocking app before peforming every request will fix it. But I don't know if it's the best approach.

**Comment by karneaud** [comment]
Was this ever solved. I face the same issue....very strange. Does it have to do with not closing the connection from the last request?

**Comment by SvOzMaS** [comment]
I'm having an issue and I think it's related to this one.
In my case I have a test class (SessionTest.php) with two methods (testRegister and testLogin), both of them with their own dataProvider.

Only the first dataset of the first method gives the expected value for the response, the other ones gives 404, even in the second method.

Any idea about how to fix this issue?

I attach two files to explains it in a better way.

![image](https://cloud.githubusercontent.com/assets/12135373/13555764/261c8cd8-e3c9-11e5-9e8d-35384a428f67.png)

![image](https://cloud.githubusercontent.com/assets/12135373/13555793/cf191bee-e3c9-11e5-91bd-dcca72bffca7.png)

**Comment by karneaud** [comment]
@SvOzMaS just to be sure....did you try running test one at a time? just to eliminate other possibilities

**Comment by SvOzMaS** [comment]
@karneaud yes, I ran all the test one by one, and all of them output the expected response. The problem comes when I try to run all the method tests with multiple data sets in the DataProvider.

**Comment by karneaud** [comment]
Ok cool. Just checking. I was not able to fix this though...hoping the author will have some good news
