### ISSUE TITLE
Not able to access headers within the app when testing

### ISSUE THREAD

**Issue by pedrofaustino** [there4/slim-unit-testing-example#12]
Hi @craig-davis, I'm not able to access the Referer header within the app when testing:

Sample code:
```

$app->get('/issue', function () use ($app) {
    $referer = $app->request->headers('referer');
    $response = $referer ? $referer : 'Missing referer header';
    $app->response->write($response);
});
```

Sample test:
```
public function testWithRefererWithPii()
    {
        $qs = array('');
        $referer = array('Referer' => 'hello');
        $this->client->get('/issue', $qs, $referer);
        $this->assertEquals('hello', $this->client->response->body());
    }
```

The phpunit results are:
```
There was 1 failure:

1) FilterPiiTest::testWithRefererWithPii
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'hello'
+'Missing referer header'

/vagrant/tests/FilterPiiTest.php:48
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:186
phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:138
                                     
FAILURES!                            
Tests: 2, Assertions: 1, Failures: 1.
```

Any ideas?

**Comment by craig-davis** [comment]
I think we need to check the Slim docs or have a peak at the source. I think that the Slim method to fetch the referrer is 'getReferrer()' and follows the two r's spelling rather than the Apache single R. 

That said, because you're handing the `$referer` into the `get()` as a a header, I'd expect it to be in the `$app->request->headers` just as you've done. I don't see anything immediately wrong. The testing client is handled over here: https://github.com/there4/slim-test-helpers/blob/master/src/There4/Slim/Test/WebTestClient.php#L28

I'll try to carve some time out later today to look at this. In the meantime, can you repeat the same behavior with other headers?

**Comment by pedrofaustino** [comment]
The code `$app->request->headers` is running fine on production, it's just failing during the unit tests. I removed the code some time ago, had to use another method (now phpunit spins a webserver and we use guzzle to make "real" http requests). Thanks for your swift answer.

**Comment by craig-davis** [comment]
I think it's worth sorting out - something is up if it's not working. I took a quick look at the source of the `Slim\Environment::mock` and don't see anything amiss. I'll add this test to the project tonight and see if I can replicate the behavior that you're seeing.

**Comment by craig-davis** [comment]
I've just added your test to the repo and updated it to work correctly. [The key change](https://github.com/there4/slim-unit-testing-example/blob/master/tests/regression/ReferrerTest.php#L9) is in using `HTTP_REFERER`. I'll admit that I had to go look at [the Slim source](https://github.com/codeguy/Slim/blob/master/Slim/Http/Headers.php#L74) to extract that bit of knowledge. You'll notice that the Header class extends the Set Helper - and that calls the [normalize](https://github.com/codeguy/Slim/blob/4906b77a07c7bd6ff1a99aea903e940a2d4fa106/Slim/Http/Headers.php#L94).

**Comment by pedrofaustino** [comment]
Thanks @craig-davis , nicely done!

**Comment by craig-davis** [comment]
Thanks for writing such a great test case and clearly explaining it well. Always great to see people using this little project. Let me know if anything comes up or if you've got ideas to extend it.
