### ISSUE TITLE
Slim::getInstance

### ISSUE THREAD

**Issue by dasgarner** [there4/slim-unit-testing-example#13]
Firstly, thanks for the excellent guidance! I have been struggling with Slim integration testing for some time and this proved very useful indeed.

I did come across something that kept me occupied for a few hours - not a bug, but maybe worth mentioning.

I use `Slim::getInstance()` in my controllers, because I use the `Class:method` route syntax to keep things tidy. I know Slim can be injected in Slim3 using the home container, but I don't think so in Slim2.

When running a test class through phpunit, the first test succeeds but subsequent ones fail for no obvious reason. It turns out that `Slim::getInstance()` will always return the instance from the first test, unless passed a name.

bootstrap:
``` php
public function getSlimInstance()
{
    $app = new Slim(array(
          'mode' => 'testing'
     ));
     $app->setName('test');

     return $app;
}
```

The first time `new Slim()` is called the instance is stored in a protected static array inside `Slim` against the key "default". `setName` then adds another reference in the same array under the key "test".

Calling `Slim::getInstance()` returns the object from `default` which will always be the first one.

I solved it in a horrible way - tracked the application name in a static variable, so I can call `Slim::getInstance(NAME)`

Anyway - thought this might be useful to know!

**Comment by dasgarner** [comment]
A better solution:

```
class SlimHelper extends Slim
{
    public static function clearInstances()
    {
        self::$apps = [];
    }
}
```

Then in `getSlimInstance()`, `SlimHelper::clearInstances();`

**Comment by dasgarner** [comment]
I see this has all been addressed in [slim-test-helpers](https://github.com/there4/slim-test-helpers) in a far better way :smile: 

I'll close this!
Thanks

**Comment by masterzen** [comment]
@dasgarner have you tested it actually fixes your original problem (it does for me but better be safe than sorry) :)

**Comment by dasgarner** [comment]
Yes, it does indeed - can't believe I didn't think of `->setName('default')`

Amusingly I also ran into `$app->environment` being cached between requests and managed to fix it with changes in WebTestClient:

```
// Prepare a mock environment
        $this->app->environment = Slim\Environment::mock(array_merge($options, $optionalHeaders));
        $this->app->request = new Slim\Http\Request($this->app->environment);
```

However I see you also fixed that too!

So thanks very much :smile:

**Comment by masterzen** [comment]
@dasgarner, you're welcome, thanks!
